export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';

export const SHOW_DROPDOWN = 'SHOW_DROPDOWN';

export const LOADING_DATA_START = 'LOADING_DATA_START';
export const LOADING_DATA_SUCCESS = 'LOADING_DATA_SUCCESS';
export const LOADING_DATA_FAIL = 'LOADING_DATA_FAIL';

export const SELECT_START_DATE='SELECT_START_DATE';
export const SELECT_END_DATE='SELECT_END_DATE';
export const SELECT_COUNTRY='SELECT_COUNTRY';
export const SELECT_COUNTRY_KEY='SELECT_COUNTRY_KEY';
export const SELECT_COUNTRY_END_DATE_KEY='SELECT_COUNTRY_END_DATE_KEY';

export const CAT_SPEAK='CAT_SPEAK';

