export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_SUCCESS_FALSE = 'SUBMIT_ORDER_SUCCESS_FALSE';
export const SUBMIT_ORDER_FAIL = 'SUBMIT_ORDER_FAIL';
export const SHOW_SHOPPING_SUMMARY_MODAL_ACTION='SHOW_SHOPPING_SUMMARY_MODAL_ACTION';
export const CLOSE_SHOPPING_SUMMARY_MODAL_ACTION='CLOSE_SHOPPING_SUMMARY_MODAL_ACTION';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

//action types for testing
export const TEST1='TEST1';
export const ADD_COW='ADD_COW';
export const ADD_ANIMAL='ADD_ANIMAL';

